name: Load Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Log Current Directory
        run: pwd
      
      - name: Install Prisma and Client
        run: pnpm i prisma @prisma/client
        working-directory: GLF-Backend-

      - name: Reset and Seed Database
        run: npx prisma migrate reset --force
        env:
          LOAD_TEST_DATABASE_URL: ${{ secrets.LOAD_TEST_DATABASE_URL }}
        working-directory: GLF-Backend-

      - name: Artillery Backend Load Test
        uses: artilleryio/action-cli@v1
        with:
          command: run --config tests/config/configBackend.yml tests/scenarios/combinedScenarios.yml --target=${{ secrets.API_TARGET }} --name "Full-Load-Test" --record --key ${{ secrets.ARTILLERY_API_KEY }}