name: Load Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Artillery:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Install Artillery
        run: npm install -g artillery@latest

      - name: Check if Artillery API Key is set
        run: |
          if [ -z "${{ secrets.ARTILLERY_API_KEY }}" ]; then
            echo "Error: ARTILLERY_API_KEY is not set."
            exit 1
          fi

      - name: Backend Load Test
        run: |
          for scenarioFile in `ls tests/scenarios/*.yml` ; do
            artillery run --config tests/config/configBackend.yml tests/scenarios/$scenarioFile --name "Backend Load Testing" --record --key ${{ secrets.ARTILLERY_API_KEY }}
          done
        env:
          API_TARGET: ${{ secrets.API_TARGET }}
          ARTILLERY_API_KEY: ${{ secrets.ARTILLERY_API_KEY }}