name: Load Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Artillery Backend Load Test
        uses: artilleryio/action-cli@v1
        with:
          command: run --config tests/config/configBackend.yml tests/scenarios/combinedScenarios.yml --target=${{ secrets.API_TARGET }} --name "Full-Load-Test" --record --key ${{ secrets.ARTILLERY_API_KEY }}

  FrontEndArtillery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g artillery
          npm install @playwright/test
          npx playwright install --with-deps

      - name: Artillery Frontend Load Test
        run: |
          artillery run tests/config/configFrontend.yml --output frontend-test-report.json
        env:
          PLAYWRIGHT_HEADLESS: "true"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: frontend-test-results
          path: frontend-test-report.json
