name: Load Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Artillery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Artillery Backend Load Test
        uses: artilleryio/action-cli@v1
        with:
          command: run --config tests/scenarios/combinedScenarios.yml --target=${{ secrets.API_TARGET }} --name "Full Backend Load Testing" --record --key ${{ secrets.ARTILLERY_API_KEY }}
